export interface HistoricalPlace {
  historicalName: string
  period: string
  description: string
  modernEquivalent: string
  modernCountries: string[]
  region: string
}

export const REGIONS = [
  'Middle East & Mesopotamia',
  'Mediterranean & North Africa',
  'Europe',
  'Central & South Asia',
  'East & Southeast Asia',
  'Africa',
  'The Americas',
] as const

export const geographyData: HistoricalPlace[] = [
  // ── Middle East & Mesopotamia ──────────────────────────────────────────────
  {
    historicalName: 'Mesopotamia',
    period: '3500–500 BCE',
    description: 'The "land between the rivers" (Tigris and Euphrates); birthplace of writing, cities, and law. Home to Sumer, Akkad, Babylon, and Assyria.',
    modernEquivalent: 'Iraq, eastern Syria, southeastern Turkey',
    modernCountries: ['Iraq', 'Syria', 'Turkey'],
    region: 'Middle East & Mesopotamia',
  },
  {
    historicalName: 'Sumer',
    period: '4500–2000 BCE',
    description: 'The world\'s first urban civilization, in the southernmost part of Mesopotamia. Cities included Ur, Uruk, Eridu, and Lagash.',
    modernEquivalent: 'Southern Iraq',
    modernCountries: ['Iraq'],
    region: 'Middle East & Mesopotamia',
  },
  {
    historicalName: 'Akkad',
    period: '2334–2154 BCE',
    description: 'Region of northern Mesopotamia and capital city of Sargon of Akkad\'s empire — the world\'s first multi-ethnic empire.',
    modernEquivalent: 'Central Iraq',
    modernCountries: ['Iraq'],
    region: 'Middle East & Mesopotamia',
  },
  {
    historicalName: 'Babylonia',
    period: '2000–500 BCE',
    description: 'Mesopotamian kingdom centered on the city of Babylon. Under Hammurabi, produced the earliest comprehensive law code.',
    modernEquivalent: 'Central and southern Iraq',
    modernCountries: ['Iraq'],
    region: 'Middle East & Mesopotamia',
  },
  {
    historicalName: 'Assyria',
    period: '2600–612 BCE',
    description: 'Mesopotamian empire centered in northern Iraq. At its height under Tiglath-Pileser III and Ashurbanipal, it dominated the entire Middle East.',
    modernEquivalent: 'Northern Iraq, northeastern Syria, southeastern Turkey',
    modernCountries: ['Iraq', 'Syria', 'Turkey'],
    region: 'Middle East & Mesopotamia',
  },
  {
    historicalName: 'Elam',
    period: '3200–539 BCE',
    description: 'Ancient civilization east of Mesopotamia; rival and trading partner of Sumer and Babylon. Capital at Susa.',
    modernEquivalent: 'Southwestern Iran (Khuzestan province)',
    modernCountries: ['Iran'],
    region: 'Middle East & Mesopotamia',
  },
  {
    historicalName: 'Persia / Achaemenid Empire',
    period: '550–330 BCE',
    description: 'The largest empire of the ancient world under Cyrus, Darius, and Xerxes, stretching from Greece to India.',
    modernEquivalent: 'Iran, with territory spanning Egypt to Pakistan',
    modernCountries: ['Iran', 'Iraq', 'Turkey', 'Egypt', 'Pakistan', 'Afghanistan', 'Uzbekistan'],
    region: 'Middle East & Mesopotamia',
  },
  {
    historicalName: 'Media',
    period: '700–550 BCE',
    description: 'Iranian empire that destroyed Assyria (with Babylon) in 612 BCE before being absorbed by Cyrus the Great.',
    modernEquivalent: 'Northwestern and central Iran',
    modernCountries: ['Iran'],
    region: 'Middle East & Mesopotamia',
  },
  {
    historicalName: 'Parthia',
    period: '247 BCE–224 CE',
    description: 'Iranian empire that succeeded the Seleucids and rivaled Rome for three centuries, controlling the Silk Road.',
    modernEquivalent: 'Iran, Iraq, parts of Central Asia',
    modernCountries: ['Iran', 'Iraq', 'Turkmenistan'],
    region: 'Middle East & Mesopotamia',
  },
  {
    historicalName: 'Sasanian Empire',
    period: '224–651 CE',
    description: 'The last pre-Islamic Persian empire; a peer rival to Rome and Byzantium, patron of Zoroastrianism and Persian culture.',
    modernEquivalent: 'Iran, Iraq, and surrounding regions',
    modernCountries: ['Iran', 'Iraq', 'Armenia', 'Azerbaijan', 'Afghanistan', 'Pakistan'],
    region: 'Middle East & Mesopotamia',
  },
  {
    historicalName: 'Canaan',
    period: '3000–1200 BCE',
    description: 'Bronze Age region between the Jordan River and the Mediterranean, inhabited by Canaanites; later the setting of Israelite history.',
    modernEquivalent: 'Israel, Palestinian Territories, Lebanon, western Jordan, southwestern Syria',
    modernCountries: ['Israel', 'Palestine', 'Lebanon', 'Jordan', 'Syria'],
    region: 'Middle East & Mesopotamia',
  },
  {
    historicalName: 'Phoenicia',
    period: '1500–300 BCE',
    description: 'Maritime civilization of city-states (Tyre, Sidon, Byblos) that invented the alphabet and founded Carthage.',
    modernEquivalent: 'Lebanon and coastal Syria',
    modernCountries: ['Lebanon', 'Syria'],
    region: 'Middle East & Mesopotamia',
  },
  {
    historicalName: 'Judea / Judah',
    period: '930 BCE–135 CE',
    description: 'Southern Hebrew kingdom after the split from Israel; later a Roman province. Center of Judaism and the birth of Christianity.',
    modernEquivalent: 'Southern Israel and the West Bank',
    modernCountries: ['Israel', 'Palestine'],
    region: 'Middle East & Mesopotamia',
  },
  {
    historicalName: 'Nabataean Kingdom',
    period: '400 BCE–106 CE',
    description: 'Arab trading kingdom whose capital Petra (in modern Jordan) controlled lucrative caravan routes. Famous for rock-cut architecture.',
    modernEquivalent: 'Jordan, northwestern Saudi Arabia, southern Israel',
    modernCountries: ['Jordan', 'Saudi Arabia', 'Israel'],
    region: 'Middle East & Mesopotamia',
  },
  {
    historicalName: 'Arabia Felix',
    period: '1000 BCE–600 CE',
    description: '"Fertile Arabia" — the prosperous southern Arabian kingdoms (Saba/Sheba, Himyar) that controlled the frankincense and myrrh trade.',
    modernEquivalent: 'Yemen',
    modernCountries: ['Yemen'],
    region: 'Middle East & Mesopotamia',
  },
  {
    historicalName: 'Levant',
    period: 'Antiquity–present (as geographic term)',
    description: 'Broad term for the eastern Mediterranean coastlands — a crossroads of civilizations, empires, and trade routes throughout history.',
    modernEquivalent: 'Syria, Lebanon, Israel, Palestinian Territories, Jordan',
    modernCountries: ['Syria', 'Lebanon', 'Israel', 'Palestine', 'Jordan'],
    region: 'Middle East & Mesopotamia',
  },

  // ── Mediterranean & North Africa ──────────────────────────────────────────
  {
    historicalName: 'Anatolia',
    period: 'Antiquity–1923',
    description: 'The large peninsula forming most of modern Turkey; home to Hittites, Lydians, Greeks, Romans, Byzantines, and Seljuks before becoming the core of modern Turkey.',
    modernEquivalent: 'Turkey (Asian part)',
    modernCountries: ['Turkey'],
    region: 'Mediterranean & North Africa',
  },
  {
    historicalName: 'Hatti / Hittite Empire',
    period: '1700–1200 BCE',
    description: 'Bronze Age Anatolian empire that fought Egypt to a stalemate at Kadesh and mastered iron smelting.',
    modernEquivalent: 'Central and northern Turkey',
    modernCountries: ['Turkey'],
    region: 'Mediterranean & North Africa',
  },
  {
    historicalName: 'Lydia',
    period: '1200–546 BCE',
    description: 'Anatolian kingdom credited with inventing coinage (~600 BCE). Its last king Croesus became proverbial for wealth.',
    modernEquivalent: 'Western Turkey (Aegean region)',
    modernCountries: ['Turkey'],
    region: 'Mediterranean & North Africa',
  },
  {
    historicalName: 'Ionia',
    period: '1000–300 BCE',
    description: 'Greek settlements on the western coast of Anatolia; birthplace of philosophy (Thales, Heraclitus, Anaximander).',
    modernEquivalent: 'Western Turkey (Izmir region and coast)',
    modernCountries: ['Turkey'],
    region: 'Mediterranean & North Africa',
  },
  {
    historicalName: 'Thrace',
    period: '500 BCE–46 CE',
    description: 'Region between the Aegean, Black Sea, and Danube; contested among Greeks, Macedonians, and Romans before Roman annexation.',
    modernEquivalent: 'Bulgaria, northeastern Greece, European Turkey',
    modernCountries: ['Bulgaria', 'Greece', 'Turkey'],
    region: 'Mediterranean & North Africa',
  },
  {
    historicalName: 'Macedonia',
    period: '800–168 BCE',
    description: 'Greek-speaking kingdom north of Greece that under Philip II and Alexander the Great conquered the Persian Empire.',
    modernEquivalent: 'North Macedonia and northern Greece (Greek Macedonia)',
    modernCountries: ['North Macedonia', 'Greece'],
    region: 'Mediterranean & North Africa',
  },
  {
    historicalName: 'Illyria',
    period: '400 BCE–9 CE',
    description: 'Region of the western Balkans inhabited by Illyrian tribes; conquered by Rome after prolonged wars.',
    modernEquivalent: 'Albania, Kosovo, western North Macedonia, parts of former Yugoslavia',
    modernCountries: ['Albania', 'Kosovo', 'North Macedonia', 'Serbia', 'Croatia', 'Bosnia and Herzegovina'],
    region: 'Mediterranean & North Africa',
  },
  {
    historicalName: 'Dacia',
    period: '200 BCE–106 CE',
    description: 'Kingdom of the Dacians conquered by Emperor Trajan in 106 CE; Romanization gave rise to the Romanian language.',
    modernEquivalent: 'Romania, Moldova, and parts of Hungary and Bulgaria',
    modernCountries: ['Romania', 'Moldova'],
    region: 'Mediterranean & North Africa',
  },
  {
    historicalName: 'Carthage',
    period: '814–146 BCE',
    description: 'Phoenician colony that became the dominant maritime power of the western Mediterranean before destruction by Rome.',
    modernEquivalent: 'Northern Tunisia (near modern Tunis)',
    modernCountries: ['Tunisia'],
    region: 'Mediterranean & North Africa',
  },
  {
    historicalName: 'Numidia',
    period: '200–46 BCE',
    description: 'Berber kingdom in North Africa; King Jugurtha was a formidable opponent of Rome before defeat. Later a Roman province.',
    modernEquivalent: 'Northern Algeria and northeastern Tunisia',
    modernCountries: ['Algeria', 'Tunisia'],
    region: 'Mediterranean & North Africa',
  },
  {
    historicalName: 'Mauretania (ancient)',
    period: '3rd century BCE–40 CE',
    description: 'Berber kingdom west of Numidia; absorbed into the Roman Empire under Emperor Claudius as two provinces.',
    modernEquivalent: 'Northern Morocco and northwestern Algeria',
    modernCountries: ['Morocco', 'Algeria'],
    region: 'Mediterranean & North Africa',
  },
  {
    historicalName: 'Hispania',
    period: '218 BCE–476 CE',
    description: 'Roman name for the Iberian Peninsula. Conquered during the Punic Wars; birthplace of emperors Trajan and Hadrian.',
    modernEquivalent: 'Spain and Portugal',
    modernCountries: ['Spain', 'Portugal'],
    region: 'Mediterranean & North Africa',
  },
  {
    historicalName: 'Al-Andalus',
    period: '711–1492 CE',
    description: 'Muslim-ruled territory of the Iberian Peninsula; at its height a center of learning, philosophy, and cultural synthesis.',
    modernEquivalent: 'Spain and Portugal',
    modernCountries: ['Spain', 'Portugal'],
    region: 'Mediterranean & North Africa',
  },
  {
    historicalName: 'Cyrenaica',
    period: '630 BCE–present (as region)',
    description: 'Greek and later Roman region of North Africa centered on the city of Cyrene; major source of silphium plant.',
    modernEquivalent: 'Eastern Libya',
    modernCountries: ['Libya'],
    region: 'Mediterranean & North Africa',
  },

  // ── Europe ────────────────────────────────────────────────────────────────
  {
    historicalName: 'Gaul (Gallia)',
    period: '300 BCE–486 CE',
    description: 'Roman province encompassing Celtic peoples west of the Rhine; conquered by Julius Caesar 58–50 BCE. Romanization gave rise to French culture.',
    modernEquivalent: 'France, Belgium, Luxembourg, Switzerland, and parts of Germany',
    modernCountries: ['France', 'Belgium', 'Luxembourg', 'Switzerland', 'Germany'],
    region: 'Europe',
  },
  {
    historicalName: 'Britannia',
    period: '43–410 CE',
    description: 'Roman province covering most of modern England and Wales. Hadrian\'s Wall marked its northern frontier.',
    modernEquivalent: 'England and Wales (United Kingdom)',
    modernCountries: ['United Kingdom'],
    region: 'Europe',
  },
  {
    historicalName: 'Caledonia',
    period: 'Roman era',
    description: 'Roman term for the territory north of Hadrian\'s Wall, never conquered. Home to Pictish and other Celtic peoples.',
    modernEquivalent: 'Scotland',
    modernCountries: ['United Kingdom'],
    region: 'Europe',
  },
  {
    historicalName: 'Hibernia',
    period: 'Roman era onward',
    description: 'Roman name for the island never conquered by Rome; center of Celtic Christian culture in the early medieval period.',
    modernEquivalent: 'Ireland',
    modernCountries: ['Ireland', 'United Kingdom'],
    region: 'Europe',
  },
  {
    historicalName: 'Germania',
    period: '1st century BCE–5th century CE',
    description: 'Roman term for the territory east of the Rhine and north of the Danube; never fully conquered (see: Battle of Teutoburg Forest, 9 CE).',
    modernEquivalent: 'Germany, Austria, Netherlands, and parts of Eastern Europe',
    modernCountries: ['Germany', 'Austria', 'Netherlands', 'Poland', 'Czech Republic'],
    region: 'Europe',
  },
  {
    historicalName: 'Pannonia',
    period: '9 CE–433 CE',
    description: 'Roman province along the middle Danube; key frontier against Germanic and steppe peoples.',
    modernEquivalent: 'Hungary, eastern Austria, Slovenia, Croatia, northern Serbia',
    modernCountries: ['Hungary', 'Austria', 'Slovenia', 'Croatia', 'Serbia'],
    region: 'Europe',
  },
  {
    historicalName: 'Bohemia',
    period: 'Medieval–1918',
    description: 'Kingdom in Central Europe; core of the Holy Roman Empire and Habsburg domains; site of the Defenestration of Prague that triggered the Thirty Years\' War.',
    modernEquivalent: 'Czech Republic (western portion)',
    modernCountries: ['Czech Republic'],
    region: 'Europe',
  },
  {
    historicalName: 'Burgundy',
    period: '411–1477 CE',
    description: 'Kingdom and duchy in western Europe; at its height a rival to France and a major cultural center.',
    modernEquivalent: 'Eastern France, Belgium, Luxembourg, Netherlands',
    modernCountries: ['France', 'Belgium', 'Luxembourg', 'Netherlands'],
    region: 'Europe',
  },
  {
    historicalName: 'Prussia',
    period: '1525–1947',
    description: 'Germanic state that grew from the Baltic coast to dominate northern Germany and unite the German Empire in 1871.',
    modernEquivalent: 'Northeastern Germany, Poland (Pomerania, Silesia), and Kaliningrad (Russia)',
    modernCountries: ['Germany', 'Poland', 'Russia'],
    region: 'Europe',
  },
  {
    historicalName: 'Livonia',
    period: '1207–1561',
    description: 'Crusader state and later Duchy on the eastern Baltic coast; site of Baltic German colonization.',
    modernEquivalent: 'Estonia and Latvia',
    modernCountries: ['Estonia', 'Latvia'],
    region: 'Europe',
  },
  {
    historicalName: 'Kievan Rus',
    period: '882–1240 CE',
    description: 'Medieval Slavic federation centered on Kyiv; the cultural and political ancestor of Russia, Ukraine, and Belarus.',
    modernEquivalent: 'Ukraine, Belarus, and western Russia',
    modernCountries: ['Ukraine', 'Belarus', 'Russia'],
    region: 'Europe',
  },
  {
    historicalName: 'Scythia',
    period: '900–200 BCE',
    description: 'Nomadic Iranian-speaking empire of the Eurasian steppe; famous for horse warfare and gold craftsmanship.',
    modernEquivalent: 'Ukraine, southern Russia, and Kazakhstan',
    modernCountries: ['Ukraine', 'Russia', 'Kazakhstan'],
    region: 'Europe',
  },
  {
    historicalName: 'Sarmatia',
    period: '400 BCE–400 CE',
    description: 'Nomadic Iranian confederation that succeeded Scythia on the Pontic steppe; frequently mentioned in Roman sources.',
    modernEquivalent: 'Ukraine, southern Russia, Poland, and Kazakhstan',
    modernCountries: ['Ukraine', 'Russia', 'Poland', 'Kazakhstan'],
    region: 'Europe',
  },
  {
    historicalName: 'Transylvania',
    period: 'Medieval–1918',
    description: 'Central European plateau long contested among Hungarians, Romanians, and Saxons; core of the Hungarian Kingdom.',
    modernEquivalent: 'Central Romania',
    modernCountries: ['Romania'],
    region: 'Europe',
  },
  {
    historicalName: 'Wallachia & Moldavia',
    period: '1330–1859',
    description: 'Two Danubian principalities under Ottoman suzerainty that united in 1859 to form Romania.',
    modernEquivalent: 'Romania and Moldova',
    modernCountries: ['Romania', 'Moldova'],
    region: 'Europe',
  },

  // ── Central & South Asia ──────────────────────────────────────────────────
  {
    historicalName: 'Bactria',
    period: '600 BCE–1000 CE',
    description: 'Region north of the Hindu Kush; a crossroads of Greek, Persian, Indian, and Chinese culture. Capital at Bactra (modern Balkh).',
    modernEquivalent: 'Northern Afghanistan, southern Uzbekistan, southern Tajikistan',
    modernCountries: ['Afghanistan', 'Uzbekistan', 'Tajikistan'],
    region: 'Central & South Asia',
  },
  {
    historicalName: 'Sogdia',
    period: '500 BCE–900 CE',
    description: 'Central Asian civilization of merchant city-states (Samarkand, Bukhara) that dominated Silk Road commerce for a millennium.',
    modernEquivalent: 'Uzbekistan and Tajikistan',
    modernCountries: ['Uzbekistan', 'Tajikistan'],
    region: 'Central & South Asia',
  },
  {
    historicalName: 'Transoxiana',
    period: '300 BCE–1200 CE',
    description: 'Roman/Persian term for the land "beyond the Oxus River" — one of the most cosmopolitan regions of the ancient world.',
    modernEquivalent: 'Uzbekistan, Tajikistan, southern Kazakhstan',
    modernCountries: ['Uzbekistan', 'Tajikistan', 'Kazakhstan'],
    region: 'Central & South Asia',
  },
  {
    historicalName: 'Gandhara',
    period: '600 BCE–1200 CE',
    description: 'Flourishing Buddhist kingdom at the crossroads of India, Central Asia, and China. Famous for Greco-Buddhist sculpture.',
    modernEquivalent: 'Northwestern Pakistan and eastern Afghanistan',
    modernCountries: ['Pakistan', 'Afghanistan'],
    region: 'Central & South Asia',
  },
  {
    historicalName: 'Punjab (historical)',
    period: 'Antiquity–1947',
    description: 'The "land of five rivers" — one of the most fertile and fought-over regions in Asian history; Alexander\'s easternmost conquest.',
    modernEquivalent: 'Split between Pakistan (Punjab province) and India (Punjab state)',
    modernCountries: ['Pakistan', 'India'],
    region: 'Central & South Asia',
  },
  {
    historicalName: 'Hindustan',
    period: 'Medieval–1947',
    description: 'Persian/Mughal term for the Indian subcontinent, particularly the Indo-Gangetic Plain.',
    modernEquivalent: 'India, Pakistan, and Bangladesh',
    modernCountries: ['India', 'Pakistan', 'Bangladesh'],
    region: 'Central & South Asia',
  },
  {
    historicalName: 'Deccan',
    period: 'Antiquity–present (as region)',
    description: 'The elevated plateau forming the southern and central Indian peninsula; home to Satavahana, Rashtrakuta, Vijayanagara, and Bijapur kingdoms.',
    modernEquivalent: 'Central and southern India',
    modernCountries: ['India'],
    region: 'Central & South Asia',
  },
  {
    historicalName: 'Ceylon',
    period: 'Antiquity–1972',
    description: 'Island kingdom south of India; center of Theravada Buddhism and major entrepôt in Indian Ocean trade. Name changed to Sri Lanka in 1972.',
    modernEquivalent: 'Sri Lanka',
    modernCountries: ['Sri Lanka'],
    region: 'Central & South Asia',
  },

  // ── East & Southeast Asia ─────────────────────────────────────────────────
  {
    historicalName: 'Cathay',
    period: 'Medieval (European usage)',
    description: 'Medieval European name for northern China, derived from "Khitan" — the Liao Dynasty rulers Europeans first heard of.',
    modernEquivalent: 'Northern China',
    modernCountries: ['China'],
    region: 'East & Southeast Asia',
  },
  {
    historicalName: 'Manchuria',
    period: 'Historical–present (as region)',
    description: 'Homeland of the Manchu people who founded the Qing Dynasty (1644–1912) and ruled all of China for nearly three centuries.',
    modernEquivalent: 'Northeastern China (Heilongjiang, Jilin, Liaoning provinces)',
    modernCountries: ['China'],
    region: 'East & Southeast Asia',
  },
  {
    historicalName: 'Formosa',
    period: '1544–1949 (as European/Chinese name)',
    description: 'Portuguese name for the island ("beautiful island"); later a Japanese colony (1895–1945), now the seat of the Republic of China.',
    modernEquivalent: 'Taiwan',
    modernCountries: ['Taiwan'],
    region: 'East & Southeast Asia',
  },
  {
    historicalName: 'Joseon (Chosŏn)',
    period: '1392–1897',
    description: 'Last Korean dynasty before Japanese annexation; Confucian state that created Hangul script and produced distinctive ceramic arts.',
    modernEquivalent: 'North Korea and South Korea',
    modernCountries: ['North Korea', 'South Korea'],
    region: 'East & Southeast Asia',
  },
  {
    historicalName: 'Champa',
    period: '192–1832 CE',
    description: 'Indianized coastal kingdom of central Vietnam; long rival of the Khmer and Vietnamese kingdoms.',
    modernEquivalent: 'Central Vietnam',
    modernCountries: ['Vietnam'],
    region: 'East & Southeast Asia',
  },
  {
    historicalName: 'Khmer Empire',
    period: '802–1431 CE',
    description: 'Southeast Asian empire centered at Angkor; built Angkor Wat, the world\'s largest religious monument.',
    modernEquivalent: 'Cambodia, with territory in Thailand, Laos, and Vietnam',
    modernCountries: ['Cambodia', 'Thailand', 'Laos', 'Vietnam'],
    region: 'East & Southeast Asia',
  },
  {
    historicalName: 'Siam',
    period: '1238–1939',
    description: 'Kingdom of mainland Southeast Asia; one of the few Asian nations never colonized by Europeans. Renamed Thailand in 1939.',
    modernEquivalent: 'Thailand',
    modernCountries: ['Thailand'],
    region: 'East & Southeast Asia',
  },
  {
    historicalName: 'Burma / Pagan Empire',
    period: '849–1885 CE',
    description: 'Buddhist civilization that built thousands of temples at Pagan; later colonized by Britain as "Burma"; renamed Myanmar in 1989.',
    modernEquivalent: 'Myanmar',
    modernCountries: ['Myanmar'],
    region: 'East & Southeast Asia',
  },
  {
    historicalName: 'Dutch East Indies',
    period: '1800–1949',
    description: 'Dutch colonial territory encompassing over 17,000 islands; the world\'s largest colonial possession by area at its height.',
    modernEquivalent: 'Indonesia',
    modernCountries: ['Indonesia'],
    region: 'East & Southeast Asia',
  },
  {
    historicalName: 'French Indochina',
    period: '1887–1954',
    description: 'French colonial federation in mainland Southeast Asia; dissolved after the First Indochina War and the Battle of Dien Bien Phu.',
    modernEquivalent: 'Vietnam, Laos, and Cambodia',
    modernCountries: ['Vietnam', 'Laos', 'Cambodia'],
    region: 'East & Southeast Asia',
  },

  // ── Africa ────────────────────────────────────────────────────────────────
  {
    historicalName: 'Nubia / Kush',
    period: '2500 BCE–350 CE',
    description: 'Civilization south of Egypt along the Nile; at its height the Kushite 25th Dynasty ruled all of Egypt. Capital moved from Napata to Meroë.',
    modernEquivalent: 'Northern Sudan and southern Egypt',
    modernCountries: ['Sudan', 'Egypt'],
    region: 'Africa',
  },
  {
    historicalName: 'Axum / Aksum',
    period: '100–940 CE',
    description: 'Ethiopian trading empire that adopted Christianity (~340 CE) and rivaled Rome and Persia in power. One of the ancient world\'s four great powers.',
    modernEquivalent: 'Northern Ethiopia and Eritrea',
    modernCountries: ['Ethiopia', 'Eritrea'],
    region: 'Africa',
  },
  {
    historicalName: 'Land of Punt',
    period: '2500–1000 BCE',
    description: 'Mysterious trading partner of ancient Egypt, source of myrrh, frankincense, ebony, and gold. Its precise location remains debated.',
    modernEquivalent: 'Eritrea, Ethiopia, Djibouti, and Somalia',
    modernCountries: ['Eritrea', 'Ethiopia', 'Djibouti', 'Somalia'],
    region: 'Africa',
  },
  {
    historicalName: 'Ghana Empire',
    period: '700–1240 CE',
    description: 'First major West African empire; controlled trans-Saharan gold and salt trade. Unrelated geographically to the modern country of Ghana.',
    modernEquivalent: 'Southeastern Mauritania and western Mali',
    modernCountries: ['Mauritania', 'Mali'],
    region: 'Africa',
  },
  {
    historicalName: 'Mali Empire',
    period: '1235–1600 CE',
    description: 'West African empire at its height under Mansa Musa (r. 1312–1337); controlled most of West Africa\'s gold production.',
    modernEquivalent: 'Mali, Senegal, Gambia, Guinea-Bissau, Guinea, and parts of Mauritania and Burkina Faso',
    modernCountries: ['Mali', 'Senegal', 'Gambia', 'Guinea', 'Mauritania', 'Burkina Faso'],
    region: 'Africa',
  },
  {
    historicalName: 'Songhai Empire',
    period: '1430–1591 CE',
    description: 'Largest empire in West African history; Timbuktu was a great center of Islamic scholarship under Askia Muhammad.',
    modernEquivalent: 'Mali, Niger, Senegal, Nigeria, Guinea, Burkina Faso',
    modernCountries: ['Mali', 'Niger', 'Nigeria', 'Senegal', 'Burkina Faso'],
    region: 'Africa',
  },
  {
    historicalName: 'Kingdom of Benin',
    period: '1180–1897 CE',
    description: 'Powerful West African kingdom in the Niger Delta area; renowned for its bronze castings and ivory carvings.',
    modernEquivalent: 'Southern Nigeria (Edo State)',
    modernCountries: ['Nigeria'],
    region: 'Africa',
  },
  {
    historicalName: 'Rhodesia',
    period: '1895–1980',
    description: 'British colonial territory named after Cecil Rhodes. Southern Rhodesia declared unilateral independence in 1965; became Zimbabwe in 1980.',
    modernEquivalent: 'Zimbabwe (Southern Rhodesia) and Zambia (Northern Rhodesia)',
    modernCountries: ['Zimbabwe', 'Zambia'],
    region: 'Africa',
  },
  {
    historicalName: 'Abyssinia',
    period: 'Medieval–1941',
    description: 'Historic name for the Ethiopian highland empire; used in European sources until the mid-20th century.',
    modernEquivalent: 'Ethiopia',
    modernCountries: ['Ethiopia'],
    region: 'Africa',
  },
  {
    historicalName: 'Congo Free State',
    period: '1885–1908',
    description: 'Personal property of King Leopold II of Belgium; scene of extreme colonial violence and forced labor. Became Belgian Congo, then Zaire, then DRC.',
    modernEquivalent: 'Democratic Republic of the Congo',
    modernCountries: ['Democratic Republic of the Congo'],
    region: 'Africa',
  },

  // ── The Americas ──────────────────────────────────────────────────────────
  {
    historicalName: 'Aztec Empire (Triple Alliance)',
    period: '1428–1521 CE',
    description: 'Mesoamerican empire centered at Tenochtitlán (modern Mexico City); conquered by Hernán Cortés with indigenous allies.',
    modernEquivalent: 'Central Mexico',
    modernCountries: ['Mexico'],
    region: 'The Americas',
  },
  {
    historicalName: 'Maya Civilization',
    period: '2000 BCE–1500 CE',
    description: 'Advanced Mesoamerican civilization with writing, astronomy, and monumental architecture. Classic period cities include Tikal and Palenque.',
    modernEquivalent: 'Southern Mexico, Guatemala, Belize, Honduras, El Salvador',
    modernCountries: ['Mexico', 'Guatemala', 'Belize', 'Honduras', 'El Salvador'],
    region: 'The Americas',
  },
  {
    historicalName: 'Inca Empire (Tawantinsuyu)',
    period: '1438–1533 CE',
    description: 'Largest empire in pre-Columbian America, stretching 4,300 km along the Andes. Conquered by Francisco Pizarro.',
    modernEquivalent: 'Peru, Ecuador, Bolivia, northern Chile, northwestern Argentina, southern Colombia',
    modernCountries: ['Peru', 'Ecuador', 'Bolivia', 'Chile', 'Argentina', 'Colombia'],
    region: 'The Americas',
  },
  {
    historicalName: 'New Spain',
    period: '1521–1821',
    description: 'Spanish colonial viceroyalty; the largest and most populous of Spain\'s American territories.',
    modernEquivalent: 'Mexico, Central America, Caribbean, southwestern United States, and the Philippines',
    modernCountries: ['Mexico', 'Guatemala', 'Honduras', 'El Salvador', 'Nicaragua', 'Costa Rica', 'United States'],
    region: 'The Americas',
  },
  {
    historicalName: 'New France',
    period: '1534–1763',
    description: 'French colonial territory in North America; lost to Britain after the Seven Years\' War.',
    modernEquivalent: 'Canada (Quebec, Ontario, Maritime provinces) and central United States (Louisiana territory)',
    modernCountries: ['Canada', 'United States'],
    region: 'The Americas',
  },
  {
    historicalName: 'Vinland',
    period: '~1000 CE',
    description: 'Norse settlement in North America established by Leif Erikson — the first European contact with the Americas, five centuries before Columbus.',
    modernEquivalent: 'Newfoundland, Canada (L\'Anse aux Meadows confirmed; wider extent uncertain)',
    modernCountries: ['Canada'],
    region: 'The Americas',
  },
]
